<?php
/**
 * Created by PhpStorm.
 * User: Nam Le Quy
 * Date: 10/7/2016
 * Time: 4:04 PM
 */
define('pi', 3.14);
class Hinh {
    public $chu_vi;
    public $dien_tich;
    public function tinh_chu_vi(){
        echo 'Chu vi là: ' ;
    }
    public function tinh_dien_tich(){
        echo 'Diện tích là: ' ;
    }
}
class HinhVuong extends Hinh{
    public $canh = 5;
    public function tinh_chu_vi()
    {

        parent::tinh_chu_vi(); // TODO: Change the autogenerated stub
        return $this -> canh *4 . PHP_EOL;
    }
    public function tinh_dien_tich()
    {
        parent::tinh_dien_tich(); // TODO: Change the autogenerated stub
        return $this -> canh* $this -> canh . PHP_EOL;
    }
}
class HinhTron extends Hinh{
    public $ban_kinh = 5;
    public function tinh_chu_vi()
    {
        parent::tinh_chu_vi(); // TODO: Change the autogenerated stub
        return $this -> ban_kinh *2 *pi .PHP_EOL;
    }
    public  function tinh_dien_tich()
    {
        parent::tinh_dien_tich(); // TODO: Change the autogenerated stub
        return $this -> ban_kinh * $this -> ban_kinh *pi;
    }

}

$hinhvuong = new HinhVuong();
$hinhtron = new HinhTron();
print_r($hinhvuong -> tinh_chu_vi());
print_r($hinhvuong -> tinh_dien_tich());
print_r($hinhtron -> tinh_chu_vi());
print_r($hinhtron -> tinh_dien_tich());

?>